//mutation 常量统一配置
export default {
	CATCH_IMG:'CATCH_IMG',
	CHANGE_PRODUCT: 'CHANGE_PRODUCT',
	CHANGE_OPENID: 'CHANGE_OPENID',
	CHANGE_ONLINE: 'CHANGE_ONLINE',
	CHANGE_MEDIA_ID: 'CHANGE_MEDIA_ID',
	CHANGE_BASIC_INFO: 'CHANGE_BASIC_INFO',
	CHANGE_DEVICE_STATE: 'CHANGE_DEVICE_STATE',
	CHANGE_STATE_LED: 'CHANGE_STATE_LED',
	CHANGE_STATE_BAT: 'CHANGE_STATE_BAT',
	CHANGE_STATE_OTA: 'CHANGE_STATE_OTA',
	CHANGE_STATE_CHILDLOCK: 'CHANGE_STATE_CHILDLOCK',
	CHANGE_STATE_WECHAT: 'CHANGE_STATE_WECHAT',
	CHANGE_STATE_POWER: 'CHANGE_STATE_POWER',
	CHANGE_STATE_SLEEP: 'CHANGE_STATE_SLEEP',
	CHANGE_STATE_PLAYER: 'CHANGE_STATE_PLAYER',
	CHANGE_STATE_REST_SLEEP: 'CHANGE_STATE_REST_SLEEP',
	CHANGE_STATE_SONGS: 'CHANGE_STATE_SONGS',
	CHANGE_LISTEN_ITEM: 'CHANGE_LISTEN_ITEM',
	CHANGE_LISTENING_ITEM: 'CHANGE_LISTENING_ITEM',
	CHANGE_PLAY_URL: 'CHANGE_PLAY_URL', 
	CHANGE_SHOW_PROPELLING: 'CHANGE_SHOW_PROPELLING',
	CHANGE_SEND_ITEM: 'CHANGE_SEND_ITEM', // 推送的歌曲
	CHNAGE_PLAY_LIST:'CHNAGE_PLAY_LIST', //播放专辑列表
	

	CHANGE_PLAY_MODE:'CHANGE_PLAY_MODE',//播放模式  单曲 循环 顺序

	CHANGE_STATE_POWER:'CHANGE_STATE_POWER',

	CHANGE_STATE_VERSION:'CHANGE_STATE_VERSION',

    CHANGE_STATE_OTA:'CHANGE_STATE_OTA',

    CHANGE_STATE_REST_SLEEP:'CHANGE_STATE_REST_SLEEP',

    CHANGE_STATE_SLEEP:'CHANGE_STATE_SLEEP',

    CHANGE_STATE_PLAYER_PROGRESS:'CHANGE_STATE_PLAYER_PROGRESS',

    CHANGE_STATE_STORAGE:'CHANGE_STATE_STORAGE',

    CHANGE_STATE_VOL:'CHANGE_STATE_VOL'

}